### ISSUE TITLE
Test Chambers 00 and 12 missing fizzler dialog

### ISSUE THREAD

**Issue by Deconimus** [mwpenny/portal64-still-alive#13]
#### Version of the game
 - current master branch

#### Original Hardware or Emulator?
Project64 3.0.1

#### What is the bug?
Missing "trapped" check if the player gets rid of the cube in test chamber 00.

#### Steps to reproduce the behavior:
1. In test chamber 00
2. Pick up cube.
3. Stand on button, which opens the door to the elevator shaft.
4. Throw cube through the opened door.
5. In the original game, this would cause a cutscene to play and a new cube to drop, this is missing here.

#### Screenshots
![cube](https://github.com/mwpenny/portal64-still-alive/assets/2451901/e3a7795f-f120-4a7f-a40b-df3b6421ab59)
Youtube video with the situation in original Portal: https://youtu.be/g1lJF6Wy_Xw?t=135

#### Additional context
I guess this is pretty low priority, but I'd be happy to contribute a fix for this via a PR, as I'm currently trying to figure out how things work in this codebase anyway.

**Comment by mwpenny** [comment]
I tried this in the original game and it only replaces the cube if it gets fizzled. The door usually pushes the cube out with enough force to propel it into the emancipation grill and cause a new one to drop. But if it stays in the hallway and doesn't get fizzled then the cube is not replaced and the player is trapped.

This is what the uploader of the video was trying to do, and achieves at 5:50: https://youtu.be/g1lJF6Wy_Xw?si=jA53rkHlHhMnEkD3&t=350. They even stand on the button to show the cube just beyond the door. So Portal 64 is behaving the same as the original here except for the voice line (which is something that should eventually be added, but not high priority).

One difference in 64 is that it is much easier to throw the cube beyond the door compared to the original game. The main reason is because the player can hold the cube above their head and move it down while throwing. In the original, objects stay in front of the player's body even when looking up. There was an issue about this on James' repo before it was taken down. I have a text file of smaller issues I've found that I can organize and log as GitHub issues sometime soon. That should make it easier to contribute and learn.

In the mean time, if you're looking to make this type of change, chamber 14 currently does not handle being trapped (https://www.youtube.com/watch?v=l6Xiw4jaJiY). Fixing this is similar to what you did for PR #12, but you'll also need to add a [trigger](https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/levels/level_objects/trigger.md) to the level this time. I'll be finishing chamber 14 after documenting cutscenes, so let me know if you decide to work on this so we don't step on each other's toes.

**Comment by Deconimus** [comment]
> I tried this in the original game and it only replaces the cube if it gets fizzled. The door usually pushes the cube out with enough force to propel it into the emancipation grill and cause a new one to drop. But if it stays in the hallway and doesn't get fizzled then the cube is not replaced and the player is trapped.
> 
> This is what the uploader of the video was trying to do, and achieves at 5:50: https://youtu.be/g1lJF6Wy_Xw?si=jA53rkHlHhMnEkD3&t=350. They even stand on the button to show the cube just beyond the door.

Oh, you're right. Should have watched the video until the end. Interestingly, this is not the case in Chamber 4, where it suffices to put the cube into the elevator corridor to trigger a cutscene with the "escape hatch" dialog. In chamber 4 there is no way to throw the cube through the door though, so we won't have to worry about that I suppose.

> So Portal 64 is behaving the same as the original here except for the voice line (which is something that should eventually be added, but not high priority).

How to add these voice lines could be an interesting issue in itself, I think. Since the voice lines are level-specific, it might be convenient to enable fizzler objects to trigger cutscenes or send signals on cube contact similar to buttons.

> In the mean time, if you're looking to make this type of change, chamber 14 currently does not handle being trapped (https://www.youtube.com/watch?v=l6Xiw4jaJiY). Fixing this is similar to what you did for PR #12, but you'll also need to add a [trigger](https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/levels/level_objects/trigger.md) to the level this time and create the cutscene. I'll be finishing chamber 14 after documenting cutscenes, so let me know if you decide to work on this so we don't step on each other's toes.

Thanks for the recommendation, I'll look into it.

**Comment by mwpenny** [comment]
> Interestingly, this is not the case in Chamber 4, where it suffices to put the cube into the elevator corridor to trigger a cutscene with the "escape hatch" dialog. In chamber 4 there is no way to throw the cube through the door though, so we won't have to worry about that I suppose.

I managed to get stuck in chamber 4 using the same technique as this video: https://www.youtube.com/watch?v=Qmnm3KiQZT4. So it's worth doing at some point.

> How to add these voice lines could be an interesting issue in itself, I think. Since the voice lines are level-specific, it might be convenient to enable fizzler objects to trigger cutscenes or send signals on cube contact similar to buttons.

I just went through the game and found that only chambers 0 and 12 have dialog for fizzling cubes. In both cases, the dialog is the same. So what is level-specific is not the dialog itself, but whether it plays. I can see why they didn't add it to the other chambers with cubes: they either do not have cube droppers (cubes start in level), have an escape hatch check, use a fizzler in the middle of the level (can fizzle cube without using the level's exit), or it is not possible to get the cube to the end.

I think the cleanest way to do this would be your suggestion of cutscenes triggered on fizzling of cubes - no need to introduce a "should play dialog" flag in the code, and signals are generally for actions that can continue (and would require more complex cutscenes which loop and check). Nice idea!

**Comment by Deconimus** [comment]
> I think the cleanest way to do this would be your suggestion of cutscenes triggered on fizzling of cubes. It avoids introducing a "should play dialog" flag in the fizzler code, and signals are generally for actions that can continue (plus, they would require more complex cutscenes which loop and check). Nice idea!

I was curious how this could be implemented, so I already made a working test a bit after writing my comment. I'll clean up my code changes and draft a PR later if you don't mind.

Just triggering cutscenes instead of using signals would indeed be more elegant in how to lay down the level logic. What I've learned though is, the cutscene_runner keeps track of which trigger has triggered a given cutscene, so that each cutscene is just triggered once by any given trigger object. This presents an issue, as the cutscene with the voice-lines can be triggered multiple times. Plus, only trigger objects themselves get a triggerIndex currently, so the code changes for that would be a bit more intrusive for the current codebase. Just adding signals to fizzler objects presented no real issue, as this works the same way as for button objects.

**Comment by mwpenny** [comment]
Instead of adding this signal functionality to the fizzler for use in 2 levels, what about just putting a trigger over top of it? That would be even less intrusive and maintain the current pattern of level objects being a minimal set of tools.

**Comment by Deconimus** [comment]
> You're right, this should work just as well.

Turns out not to be true, sadly. Using trigger objects presents an issue, because the fizzler may fizzle the cube before the collision with the trigger happens, therefore never setting the signal. This happened in my tests everytime if the trigger is placed to match the fizzler exactly and even if the trigger sticks out a bit:

![chamber00_trigger](https://github.com/mwpenny/portal64-still-alive/assets/2451901/e4b991bb-2042-4378-a8bb-4a61b51d271f)
![chamber12_trigger](https://github.com/mwpenny/portal64-still-alive/assets/2451901/551af67e-b20b-4277-8c90-8fe420432dbd)

Fixing this would require changes to the collision detection which would be a bit overboard for this, I think. If you're interested in looking into this, you can check out my branch for this: https://github.com/Deconimus/portal64-still-alive/tree/bug_13_fizzler_voice_lines_trigger

IMHO to achieve consistency, it would perhaps be easiest to add signals to fizzlers after all (especially since I already have a working solution for this that I think is fairly elegant).

**Comment by mwpenny** [comment]
Ah, it's because objects need to be fully inside of triggers for them to activate, and fizzlers disable collision on the fizzled object. Yes, signal-emitting fizzlers are the path of least resistance here. I've left some comments on your PR.

**Comment by mwpenny** [comment]
Implemented by #19. Thanks!
