### ISSUE TITLE
is there a way to install on windows?

### ISSUE THREAD

**Issue by jack6y** [mwpenny/portal64-still-alive#14]
basically the title

**Comment by mwpenny** [comment]
Do you mean build the game on Windows? You have a few options:

* Install Docker for Windows and follow the [Docker build instructions](https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/docker_setup.md) (ignoring the installation portion). This is the easiest.
*  Use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and follow the [Ubuntu build instructions](https://github.com/mwpenny/portal64-still-alive/blob/master/README.md#setup-and-install-dependencies)
* Use [MSYS2](https://www.msys2.org/) and hack together your own build environment (hardest)

I recommend Docker.

Also note that in #4 I will be refactoring the build system to make it easier to (re)configure and use. It will likely make Windows builds easier too. As part of that I'll also improve the build documentation.

Hope that answers your question.

**Comment by mwpenny** [comment]
It looks like you didn't copy your VPK files to the `vpk/` directory, and are missing the Modern SDK.

You need to follow the instructions in the readme.

Sorry if I wasn't clear above, but using MSYS or Cygwin isn't something supported out-of-the-box right now. It can be made to work, but requires some tinkering. If that's not something you're comfortable with then please use one of the supported options explained in the readme: WSL + Ubuntu instructions, or Docker. If you have problems with either of those feel free to open an issue.

I can understand there is some friction here for newcomers. It will be easier to use different configurations after issue #4.

**Comment by Jgoodwin64** [comment]
I love this. Keeping the development going.

**Comment by FoxbitDreamtail** [comment]
@jack6y It seems like your question is answered, if you were able to figure it out, then please close the issue as to not unnecessarily clutter the issues page.
