### ISSUE TITLE
Always keep held objects in front of player

### ISSUE THREAD

**Issue by mwpenny** [mwpenny/portal64-still-alive#27]
#### What is the enhancement?
In the original Portal, held objects are always kept in front of the player's body, regardless of view height:
https://github.com/mwpenny/portal64-still-alive/assets/9356790/ee7f8a80-79a9-46ad-9eb7-5ff9a769362b

In Portal 64, objects can be held above the player's head, allowing them to be thrown quite far:
https://github.com/mwpenny/portal64-still-alive/assets/9356790/b0ae0d40-b31d-4795-9fac-338fa4fa3a2b

Held objects should be kept in front of the player like in the original game.

**Comment by Deconimus** [comment]
This issue can be closed since #35 has been merged, right?

**Comment by mwpenny** [comment]
Yes
