### ISSUE TITLE
Cannot compile the current build. (valve.bik - Permission Denied)

### ISSUE THREAD

**Issue by brunorurz** [mwpenny/portal64-still-alive#3]
Version
Commit Id 8881e688ae2d274bfcf39ccd4c557d75903cd883

What is the bug?
Cannot compile the rom, like at all. I'm compiling it on Linux Mint 21.3. I installed everything that's needed, that being snapd (Since mint doesn't come with it) and all of the dependencies as per the "How to build" instructions. After running the make command everything seems to come together just fine until it reaches the valve.bik file (Valve intro) in the /Portal/hl2/media/ folder. As soon as that file is reached, says that "Authorization required, but no authorization protocol specified" and then spews out an "Permission Denied" error, stoping the compile.

I've tried literally anything I could. I even took out the files out of that folder and then the whole folder itself in hopes that it would at least give me a different error that the files are missing or something, but even despite the fact the the files were _literally not there_, it still gave me the same "Permission Denied" error as if they still existed. I genuinely have no idea if it was me that did something wrong or if there's something wrong with my game files or if it's a problem with the compile itself. I'm just at a loss with this. Any help would be aprecieated.

Just try compiling, no idea if it will behave the same for everyone though.

Screenshots
Pic of the whole error message before the compile just stops.
![image](https://github.com/mwpenny/portal64-still-alive/assets/71721681/8e35a579-9e50-4c64-b92b-53ec421605af)

**Comment by mwpenny** [comment]
Did you copy your game files to the `vpk` directory, or use a symlink?

Does it work if you don't run as root? It may be looking for some configuration which doesn't exist for the root user.

**Comment by brunorurz** [comment]
Full copy of the game files, no symlink. As for trying to not run it as root, let me check.

**Comment by brunorurz** [comment]
That seemed to do the trick! Thanks! Might want to specify that in the build instructions so nobody has the same problem later down the line. Once again, thank you!

**Comment by mwpenny** [comment]
Great to hear it's working. As for the docs, I can update it later, but in the mean time PRs are welcome :)

**Comment by mwpenny** [comment]
I've updated the readme in ebd7d341f756195b05eddd8f36b9e7f7bfbc01cf.
