### ISSUE TITLE
Apply blender object size to fizzlers

### ISSUE THREAD

**Issue by Deconimus** [mwpenny/portal64-still-alive#38]
#### Version of the game 
- current master

#### What is the enhancement?
Currently, fizzlers are fixed in size. Their width should be parsed from the `@fizzler` blender objects to enable wider fizzlers. This will be required for implementing level mechanics in Chamber 15.

#### Screenshots
![20240311211610_1](https://github.com/mwpenny/portal64-still-alive/assets/2451901/bc76cf6a-2962-46c8-ad29-ec4fcbbd8ae6)

**Comment by mwpenny** [comment]
Quite doable since the fizzler model is just one half (and I see you've already done it)
