### ISSUE TITLE
Add collision for Fizzler frames

### ISSUE THREAD

**Issue by Deconimus** [mwpenny/portal64-still-alive#41]
#### Version of the game 
current master

#### What is the enhancement?
Add collision for the metal "frame" (aka particle dispensers) of fizzlers.

#### Screenshots
![fizzler_frame](https://github.com/mwpenny/portal64-still-alive/assets/2451901/006674d2-935c-4906-aafb-160ce9904a5f)
(screenshot of an original portal map in hammer editor)

#### Additional context
Fizzler objects have no collision for the metal parts as of now, while in original Portal they do. This results in the player being able to walk through those parts.

Adding two dynamic collision boxes per object, the same size of the bounding box shown in the screenshot, should probably work well for this.

**Comment by mwpenny** [comment]
Other non-moving level objects like switches and buttons are good examples of how to implement this.
