### ISSUE TITLE
Decouple time interface from libultra

### ISSUE THREAD

**Issue by GiacomoGarbin** [mwpenny/portal64-still-alive#65]
We can replace libultra's `OSTime` with a `typedef ... Time` which can be library-dependent or library-independent, in which case each library implementation can define functions to convert to/from its internal time format.

Then we can add to the time interface a `gettime` function to get the _now_ time and a `difftime` function to compute the difference of two times.

There is nothing more to add beyond what @mwpenny suggested about `OSTimer` in https://github.com/mwpenny/portal64-still-alive/pull/47#issuecomment-2076240521:

> Note that the game's `OSTimer` usage is only for creating a delay - it is effectively just an asynchronous `sleep()` and can be wrapped as such

We can add to the time interface a `sleep` function which causes the calling thread to sleep until the seconds specified have elapsed.

**Comment by mwpenny** [comment]
In some cases, the game uses an `OSTime` relative to another `OSTime` (in `sceneRenderPerformanceMetrics()`), and so the underlying representation doesn't matter.

In other cases, the game converts to microseconds or nanoseconds (profiler).

For now, keeping it in its current format is fine. We may end up needing to add conversion functions down the road, but it's possible to keep it simple and just have callers add/subtract the underlying integer value and call a conversion function after the fact, rather than adding a diff function.

**Comment by GiacomoGarbin** [comment]
I wrapped `OSTimer` usage into `timeUSleep` in #66. I also removed `gLastTime` since it is not used which makes time.h libultra-independent.

> For now, keeping it in its current format is fine. We may end up needing to add conversion functions down the road, but even then it's possible to keep it simple and just have callers add/subtract the underlying integer value and call a conversion function on the result, rather than adding a diff function. Similar to the C standard library.

I was thinking about time diff functions that also encapsulate the time conversion, for example:
```
// time.h

typedef uint64_t Time;

Time timeNow();
uint64_t timeDiffU(Time start, Time end); // time diff in micro seconds
uint64_t timeDiffN(Time start, Time end); // time diff in nano seconds
```

Also, replacing `OSTime` with a `uint64_t` as in the example might be sufficient, assuming that the internal time format of other libraries can be easily converted to a `uint64_t`.

No problem leaving `OSTime` for now and/or preferring conversion functions to diff functions.

**Comment by mwpenny** [comment]
Thanks. And nice catch on the dead code.

> I was thinking about time diff functions that also encapsulate the time conversion

This makes sense and would work, although keeping time as an arithmetic type allows the following:
```c
Time t1 = ...;
Time t2 = ...;

Time diff = t1 - t2;
uint64_t us = timeMicroseconds(diff);
uint64_t ns = timeNanoseconds(diff);
```

Each conversion function can support converting a single time or a difference between times.

**Comment by GiacomoGarbin** [comment]
Probably the real reason to prefer diff functions is that `Time` can be of any type, e.g. a `struct`. Of course in this case a function should also be defined to calculate the ratio between two times.

But as said, I think defining `Time` as `uint64_t` is sufficient.

Let me know if you want me to proceed to replace `OSTime` and add the conversion functions.
