### ISSUE TITLE
Laggy/trackball control on joystick

### ISSUE THREAD

**Issue by pdxuzuki** [mwpenny/portal64-still-alive#7]
#### Version of the game

Whatever the current version is.  I just ran git pull&&make clean&&make

#### Original Hardware or Emulator?
MiSTer FPGA 8Bitdo N64 controller mod

#### What is the bug?
The controls seems to lag or have a trackball effect added as if I move the joystick beyond a certain point and snap back to center the camera keeps moving in the original direction instead of stopping.  I tested against the previous build which does not exhibit this behavior. 

#### Steps to reproduce the behavior:
1. get control of Chell
2. Make a large movement with the camera
3. Let stick snap back to center
4. Watch camera continue to move as if it had velocity

#### Screenshots
Needs movements to be seen

#### Additional context
If this is a "feature" please add a toggle because I find it makes the game unplayable.  I have never filled out a bug report on git, I am open to suggestions to improve my bug reports.

**Comment by pdxuzuki** [comment]
It seems setting deadzone all the way to 0 'fixes' the issue for me.  I tested increasing deadzone on the previous version and it does not create the same input problems.

**Comment by mwpenny** [comment]
Thanks for all of the details, this is interesting. I can't say I've experienced this myself, and I haven't changed anything related to controls, but James may have before he stopped working on the game. I'll take a look and also try to reproduce it on original hardware.

In the meantime, could you provide some more information? When you say you tried on the previous build and didn't have the problem - which version are you referring to? And was your hardware setup the same then?

Also, is this you playing at https://www.youtube.com/watch?v=wgNoN4RbXJ4? The setup seems to be the same as what you're describing and the description mentions the camera. Could you show what you mean in a video?

Thanks.

**Comment by mwpenny** [comment]
Also, for the future, a good way to identify version is using the git commit hash. In your local repository, you can run
```sh
git rev-parse HEAD
```
to see the hash of the commit you're currently on. I've been thinking about adding this information to the title screen to make it easier to report issues. Especially since this project won't be distributing pre-built patches as long as Nintendo libraries are a requirement to build.

**Comment by pdxuzuki** [comment]
Yes, that was me… Was frustrating to try and accurately fire off portals.  I saved the build.  I have a build that I made a couple days before you made the change(s) to the UV maps that does not exhibit the same issues.I tried deleting the whole portal64 directory and cloning it again, using the same VPK folder, I just moved it before deleting and I had the same problem.  I can provide the rom(s)On Jan 21, 2024, at 19:45, Matt Penny ***@***.***> wrote:﻿
Also, for the future, a good way to identify version is using the git commit hash. In your local repository, you can run
git rev-parse HEAD
to see the hash of the commit you're currently on. I've been thinking about adding this information to the title screen to make it easier to report issues. Especially since this project won't be distributing pre-built patches as long as Nintendo libraries are a requirement to build.

**Comment by pdxuzuki** [comment]
Sorry for the multiple emails. AADHD.Starting @ around 1:45 you can see I overshoot on some of my movements.  It almost looks like I’m using a gimbal.  I do okay in some parts because I think was able to minimize the problem if I kept my stick close to center.  It seems as if the further I get from center on the stick the more velocity my movement has after letting go of the stick.  But like I commented, it seems turning deadzone to 0 (all the way left?) seemed to fix the problem while increasing deadzone to full in the previous build didn’t seem to do anything. On Jan 21, 2024, at 19:44, Matt Penny ***@***.***> wrote:﻿
Thanks for all of the details, this is interesting. I can't say I've experienced this myself, and I haven't changed anything related to controls, but James may have before he stopped working on the game. I'll take a look and also try to reproduce it on original hardware.
In the meantime, could you provide some more information? When you say you tried on the previous build and didn't have the problem - which version are you referring to? And was your hardware setup the same then?
Also, is this you playing at https://www.youtube.com/watch?v=wgNoN4RbXJ4? The setup seems to be the same as what you're describing and the description mentions the camera. Could you show what you mean in a video?
Thanks.

**Comment by pdxuzuki** [comment]
I noticed a pull available so I rebuilt the rom and  it seems to be fixed.

**Comment by mwpenny** [comment]
@pdxuzki, thanks for the information.

> I have a build that I made a couple days before you made the change(s) to the UV maps that does not exhibit the same issues

Did you use the same hardware setup (including same controller) each time? And was this previous build also compiled using this repo - not the original? If yes, nothing has changed related to the controls or camera. The main differences are in some textures and how the build is run.

Speaking of - I noticed in your video that the cube and ball launcher/catcher textures were incorrect. Turns out that my environment where I authored the changes was slightly different than what the readme lists, resulting in broken textures for you and others. I've now fixed that.

**Comment by mwpenny** [comment]
Just saw your update. I'm not sure what was different, since I didn't change the controls or camera before, and my latest commit was to fix some textures. But I'm glad it's working for you. I suspect a hardware issue.

**Comment by pdxuzuki** [comment]
Exact same hardware, building and playing.  No changes except from what was downloaded during the git pull.On Jan 22, 2024, at 10:59, Matt Penny ***@***.***> wrote:﻿
Just saw your update. I'm not sure what was different, since I didn't change the controls or camera before, and my latest commit was to fix some textures. But I'm glad it's working for you. I suspect a hardware issue.

**Comment by mwpenny** [comment]
Very strange. I'm not sure. Feel free to re-open if you encounter it again.
