### ISSUE TITLE
Major Compilation Issue on linux Mint 21.3(I haven't been offered to upgrade yet)

### ISSUE THREAD

**Issue by FoxbitDreamtail** [mwpenny/portal64-still-alive#79]
#### Version of the game
N/A

#### Original Hardware or Emulator?
N/A

#### What is the bug?
```
~/portal64 $ make
find: ‘portal_pak_dir/’: No such file or directory
Makefile:623: warning: overriding recipe for target 'clean'
/usr/include/n64/make/commonrules:56: warning: ignoring old recipe for target 'clean'
vpk -x portal_pak_dir vpk/Portal/portal/portal_pak_dir.vpk
make: vpk: No such file or directory
make: *** [Makefile:173: portal_pak_dir] Error 127

~/portal64 $ ls
asm     build       documentation  Makefile         make_release_build.sh  README.md    src    vpk
assets  Dockerfile  LICENSE        Makefile.docker  portal.ld              skelatool64  tools
```
both of these are terminal outputs when following the compilation instructions line for line

#### Steps to reproduce the behavior:
1. Install Git(if you havn't already)
2. Install Portal Via the Linux Native Steam Client
3. Follow instructions 1:1 as stated in the README.md
4. Run make and see the error.

**Comment by hackgrid** [comment]
"vpk: No such file or directory" <- check why the python tool "vpk" could not be installed correctly.

```
# Install pipx packages
sudo apt install pipx -y
pipx ensurepath --force
pipx install vpk
```

**Comment by mwpenny** [comment]
Thanks for responding to this so quickly.

Another possibility is that `vpk` is installed but it is reporting that it can't find a file. In addition to what hackgrid suggested, also check that you have copied your Portal game files to `vpk/`.

**Comment by FoxbitDreamtail** [comment]
> Thanks for responding to this so quickly.
> 
> Another possibility is that `vpk` is installed but it is reporting that it can't find a file. In addition to what hackgrid suggested, also check that you have copied your relevant Portal game files to `vpk/` per the readme and [vpk/add_vpk_here.md](https://github.com/mwpenny/portal64-still-alive/blob/master/vpk/add_vpk_here.md).

Originally I didn't understand by what portal file it suggested. So I tried the portal file within the portal file and seeing as it erred out and gave me the extended file system in which it was expecting. I then realized that I needed to give it the root portal file from Steam. Don't know why you would need the executable there though. You aren't using the linux exexutable.... Once I figured that out, I ended up copying the entirety of my Portal folder to the project vpk folder, all four gigabytes of it, and then I got this error.

I will try what hackgrid suggested here in a minute, as I am currently trying to put my younger siblings down to bed, then I will be attempting what hackgrid suggested.

**Comment by FoxbitDreamtail** [comment]
> "vpk: No such file or directory" <- check why the python tool "vpk" could not be installed correctly.
> 
> ```
> # Install pipx packages
> sudo apt install pipx -y
> pipx ensurepath --force
> pipx install vpk
> ```

```
~$ Install pipx packages;sudo apt install pipx -y;pipx ensurepath --force;pipx install vpk
Command 'Install' not found, did you mean:
  command 'install' from deb coreutils (8.32-4.1ubuntu1.2)
Try: sudo apt install <deb name>
[sudo] password for foxbitplayz:             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pipx is already the newest version (1.0.0-1).
The following packages were automatically installed and are no longer required:
  audacity-data libid3tag0 libportsmf0v5 libsuil-0-0 libvamp-hostsdk3v5
  libwxgtk3.0-gtk3-0v5
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Success! Added /home/foxbitplayz/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for
instructions.

Otherwise pipx is ready to go! ✨ 🌟 ✨
'vpk' already seems to be installed. Not modifying existing installation in
'/home/foxbitplayz/.local/pipx/venvs/vpk'. Pass '--force' to force
installation.
```
this is the output when that set of commands is run, I have a habit of using ";" in-between each command, it does the same as " && " with less characters.

**Comment by FoxbitDreamtail** [comment]
huh, weird, I just tried it again, re-obtaining files and it worked? a weird bug, sorry for wasting your time.

Fun fact, I was one of the original testers of the original project by James Lambert! Happy to be on-board!

**Comment by mwpenny** [comment]
Glad you could get it building, and are familiar with the game. Finding and logging bugs/issues is helpful.

You don't need to copy the entire game folder, just the files listed here https://github.com/mwpenny/portal64-still-alive/blob/d6af2ebb46a8dfda242c4497e0df293347ae185a/vpk/add_vpk_here.md#add-multipal-subtile-languages. With all languages, it comes in around 2 GB. Also mentioned in the linked doc: if you're not using Docker and want to save the space, you can create a symbolic link to your original game directory instead of copying.

I can see how the heading at the above link could be ambiguous. It could potentially sound like that part is only required for multiple languages, but it's referring to just the "\<your desired language>" text files. I've updated the document: https://github.com/mwpenny/portal64-still-alive/blob/master/vpk/add_vpk_here.md.
