### ISSUE TITLE
Better match movement physics of original game

### ISSUE THREAD

**Issue by brunorurz** [mwpenny/portal64-still-alive#8]
What is the enhancement?
Self explanatory. I've always felt that the walking speed was way slower than the original game. It's probably a leftover from the very early builds of the port where player speed wasn't too important. A slight increase to match the speed of the original would be a welcome change.

Edit: The "enhancement" label didn't add for some reason. Oh, well.

**Comment by mwpenny** [comment]
Hi there. Polish like is a good idea.

PRs are welcome, but I myself won't be prioritizing smaller items like this right away. They are, however, important for making the game feel whole and should be implemented at some point.

Please feel free to log issues like this as they come up so they can be tracked and eventually worked on.

**Comment by hackgrid** [comment]
I think there was a issue about that on vanilla portal64, and the walking speed was the same as in the original game. But other factors may let it feel different.

**Comment by hackgrid** [comment]
No, sorry! It would be great if James could provide all the issues and discussion of his repo, so much useful stuff in there.

**Comment by hackgrid** [comment]
https://github.com/mwpenny/portal64-still-alive/blob/ebd7d341f756195b05eddd8f36b9e7f7bfbc01cf/src/player/player.c#L43

Player speed is defined there, and according to google the default movement speed for Portal 1 is 150, so it should match.

**Comment by mwpenny** [comment]
Yeah it's unfortunate. I did, however, find some snapshots on Archive.org:
* Older (November), but has the issue details: https://web.archive.org/web/20231118181432/Github.com/lambertjamesd/portal64/issues
* Newer (January), but does not have issue details or multiple pages: https://web.archive.org/web/20240104142322/https://20240104142322/Github.com/lambertjamesd/portal64/issues 

I'm hopeful that once there is more progress here, more people will play and report things so we'll have the equivalent.

Right now I'm mainly doing research, changes that will allow me to learn, and changes under the hood to get ready for larger ones. Slowly but surely :)

**Comment by mwpenny** [comment]
@hackgrid thanks for taking a look.


@brunorurz a video comparing the same movement in both games would make it easier to see what you're talking about and track down the "other factors" mentioned above.

**Comment by brunorurz** [comment]
https://github.com/mwpenny/portal64-still-alive/assets/71721681/7f20726f-0df9-45da-9416-5eb757a69fa0



@mwpenny I went ahead and tried to directly compare the speeds. It seems that the speed is pretty much the same actually (Only a tiny bit slower than the original). For some reason it _felt_ much slower doing it separately. I guess it's just a placebo effect in the end unless there's something more at play here (Probably isn't but who knows).

**Comment by mwpenny** [comment]
That's a very good/clear comparison, thanks! Maybe it's other parts that feel slow which make it easy to associate with the movement as a whole. For example, joystick camera movement instead of a mouse.

Also, I find myself not yet able to move through the game as confidently on N64 as I can with Portal on PC. Or even other first-person N64 games like Goldeneye. I have to think about it more consciously. Probably because the Turok-style control scheme isn't as ingrained in me as some others. That could be part of it. Not slower movement, but having to play it more slowly.

Do you feel the same way with different control schemes? For example, joystick to move and C buttons to look, or tank controls. Maybe one feels more "right" and easier to use quickly.

**Comment by mwpenny** [comment]
I've been looking at this again while fixing some issues for chamber 15. The speed is the same as the original game but the movement physics are not (acceleration, friction, etc.). Also in the original game you get a slight forward/backward boost when jumping (the cause of bunnyhopping / ABH).

Among other things, this makes some flings more difficult - the player doesn't land in the same places as they do in the original game, and the air control is not as nice.

It can hard to pinpoint while playing but the feel is definitely different. I'm working on better matching the movement physics and my results have been promising so far. I think addressing this will make it feel less sluggish.

**Comment by mwpenny** [comment]
I've implemented Source-like movement physics WRT acceleration, friction, jumping, air control, and portal funneling. I think it feels a lot closer to the original now.

It could still be polished a bit more, but improvements would be pretty subtle at this point and so they're best left for when larger pieces of work are finished and the game is closer to completion.

Give it a try!

**Comment by hackgrid** [comment]
Cool, thank you very much! :-)

**Comment by brunorurz** [comment]
Just tested the build and the movement is spot on now! Great work. Waiting for more
