### ISSUE TITLE
Snap version of Blender Use discussion

### ISSUE THREAD

**Issue by FoxbitDreamtail** [mwpenny/portal64-still-alive#80]
#### What is the bug?
Upon compiling the following errors occur:
```
/snap/bin/blender assets/models/player/chell.blend --background --python tools/export_fbx.py -- build/assets/models/player/chell.fbx
make[1]: /snap/bin/blender: No such file or directory
make[1]: *** [Makefile:442: build/assets/models/player/chell.fbx] Error 127
make[1]: Leaving directory '/home/foxbitplayz/portal64'
make: *** [Makefile:89: english_audio] Error 2
```
#### Steps to reproduce the behavior:
1. Follow Compile instructions 1:1(Making sure to copy the Portal folder from `~/.steam/debian-installation/steamapps/common/` or `SteamLibrary/steamapps/common`(for other drives with steam libraries on them) to `portal64/vpk`)
2. upon running `make` see error.

#### Additional context
It should be noted in build instructions that a version of blender is needed for compilation, many people have reservations and well deserved hatred for the Snap Package System, having the option to direct the project to an installed version of blender(System, FlatPak, Snap, Steam, Etc.) would be a much better solution than forcing people to use Cononical's Snap Package System.

**Comment by FoxbitDreamtail** [comment]
this is basically a plea to either use apt, dpkg or likewise, ***not everyone will be on unmodified ubuntu.***

**Comment by FoxbitDreamtail** [comment]
you do know that the debian system package of blender is 3.6lts right? snap is completely unnecessary.
I will try symlinking /bin/blender to /snap/bin/blender... although that feels completely unnecessary and *will* break many people's systems.

**Comment by hackgrid** [comment]
Well on Ubuntu it is not. Why do you insist on building on your local
system, just set up a VM for it or use the Docker container, like everyone
else :D

Foxbit ***@***.***> schrieb am So., 11. Aug. 2024, 22:17:

**Comment by FoxbitDreamtail** [comment]
1, I don't want to learn docker as there seems to be some glaring limitations with docker.
2, Compiling with ANY VM software(QEMU, VirtualBox, VMPlayer) is sub-optimal at best and egregiously slow at worst
3, wherever possible I would prefer not using anything from bigger tech companies, in the linux world canonical is the microsoft equivalent of the linux world...

**Comment by FoxbitDreamtail** [comment]
In any case Blender 3.0.1 did give me a working build, proving that this is a moot point at best.

**Comment by hackgrid** [comment]
Well if you want to clutter your main system with dependencies from random
github projects, feel free to do so! :) Performance differences inside a VM
are totally negligible. If you are on another distro, you cant complain,
you need to figure out this on your own. Compiling is not for end users.
Everybody could complain about not being able to install deps because their
distro lacks apt-get. All issues you submitted were problems on your system.

Foxbit ***@***.***> schrieb am So., 11. Aug. 2024, 22:36:

**Comment by FoxbitDreamtail** [comment]
ok? Compiling is *Not* just for developers considering how easy it is for a non-developer to compile cmake/make based projects. I am on Linux Mint 21.3(Have not been offered the upgrade yet), an Ubuntu derivative that is more user friendly true but you cannot expect everyone to just "Use Ubuntu" because it "Just Works!" because news flash, it does not "Just Work". Snap is *Not* a solution, if anything snap, being proprietary is a problem. I will also attempt building with Steam's Blender 4.6 to see if the low blender "requirement" is actually a requirement or a suggestion(at best).

**Comment by hackgrid** [comment]
Anything above Blender 3.6 breaks Chell model animation.
See https://github.com/lambertjamesd/portal64/issues/518

Of course Ubuntu "just works" if you use it in Docker or a VM.

If you don't like it, fix it and submit a PR.
But it will be tricky to get Blender 3.6 on all kinds of distros - even Debian unstable uses 4.+.

**Comment by FoxbitDreamtail** [comment]
ok? but I have proved that the debian blender 3.0.1 system package works. 

Also, 404 Page not found, maybe send an Archive.org link next time?

**Comment by hackgrid** [comment]
I think Blender 3.0.1 is too old, James upped the requirement for some new features she used.
Just because it compiles, it does not mean it looks as it should.

Archive.org does not have it, I checked before. Maybe it is not yours to see.

**Comment by FoxbitDreamtail** [comment]
> Archive.org does not have it, I checked before. Maybe it is not yours to see.

If archive.org doesn't have it, then archive it. isn't that the whole damn point of archiving information?!

> Just because it compiles, it does not mean it looks as it should.

besides some minor z-fighting, I saw no issues with the game aside for 1 wall not being portalable when I could swear I placed a portal on it in the main game.

**Comment by FoxbitDreamtail** [comment]
also, you can access Blender v3.6 in Steam via Steam Betas.

**Comment by hackgrid** [comment]
Feel free to install however and change your environment variable in your
bashrc to your local path

Foxbit ***@***.***> schrieb am So., 11. Aug. 2024, 23:44:

**Comment by FoxbitDreamtail** [comment]
my problem is that .bashrc doesn't seem to do anything to stop the "snap requirement", could mint be using a different system? I've been getting around this by symbolically linking different blender files to /snap/bin/blender. I will be trying Steam's version of Blender v3.6 next.

**Comment by FoxbitDreamtail** [comment]
we have gone vastly off-topic. my primary problem, and the thing keeping me from closing this issue is that the Blender requirement is **NOT MENTIONED** in the build instructions.

**Comment by hackgrid** [comment]
See
https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/manual_setup.md

Foxbit ***@***.***> schrieb am So., 11. Aug. 2024, 23:58:

**Comment by FoxbitDreamtail** [comment]
can I add a *Steam* setup option that will work on ALL Major distros?

**Comment by FoxbitDreamtail** [comment]
also, this(`Clone the Portal64 repo or download the zip.`) section is incorrect, it points to the now inaccessible old repo.

**Comment by FoxbitDreamtail** [comment]
@hackgrid @mwpenny I have added a poll request to fix what I have mentioned here.
https://github.com/mwpenny/portal64-still-alive/pull/84

**Comment by mwpenny** [comment]
Thanks @hackgrid for jumping in here. You've already answered everything. Here are my two cents:

@FoxbitDreamtail, it sounds like much of your frustration is stemming from the fact that the build doesn't work as-is on your system without either going through several manual steps or using software you don't want to use.

But you have a choice and can build the project however you like. However, maintaining instructions for and testing every possible environment is impractical. So instead we document manual instructions for using Ubuntu and provide a Dockerfile for using anything else. You're free to set it up in some other environment (I even use Windows + MSYS2 on one of my dev machines), but you'll be on your own as we can only go so far. Docker is the easiest way to support building across various platforms.

Snap is only used if you run `setup.sh`. The script is just an easy way to create a build environment that works - you don't have to use it and the build itself doesn't care how you installed Blender. If you'd like to install it another way, you can do so and just update the environment variable accordingly. I downloaded mine directly from https://www.blender.org/.

With that said, the build system will be refactored in #4 and I'm going to look into automatically discovering things like the game files, Blender, etc. to make it a bit easier. But going outside of what is supported will still be the user's responsibility.

**Comment by mwpenny** [comment]
> Can I add a Steam setup option that will work on ALL Major distros?

I think what would be most useful is more elaboration in the doc @hackgrid mentioned. For example:
> Install dependency A
> Install dependency B
> [...]
> Install Blender 3.6 via your preferred means (Steam, Snap, etc.) and set the `BLENDER_3_6` environment variable...

No need for a whole other doc since most steps will be the same anyway. We can just explain the different options at the appropriate point. The important part is just the version. We aren't prescribing how you _must_ install - just a few possible ways. Going beyond that is outside the scope.

> I will also attempt building with Steam's Blender 4.6 to see if the low blender "requirement" is actually a requirement or a suggestion(at best).

I have wondered this. I think what might have happened on the original repo is someone edited a `.blend` file with 4.x but then tried building with the Docker image, which uses 3.6. And of course loading a newer Blender file in an older version could result in data loss (as you saw with the Chell model). Looking into what would be needed for an upgrade (if anything) would be helpful since 3.6 goes EOL next year. Please create an issue to organize the discussion if you choose to go ahead with this.

> If archive.org doesn't have it, then archive it. isn't that the whole damn point of archiving information?!

In general (this comment and others) please settle down. Keep in mind this is an unpaid, volunteer project done in spare time.

**Comment by mwpenny** [comment]
Thanks for confirming. Something to look into fixing eventually then.

**Comment by FoxbitDreamtail** [comment]
> In general (this comment and others) please settle down. Keep in mind this is an unpaid, volunteer project done in spare time.

I understand that this is a volunteer project, but so is the internet archive(it's a non-profit but same-difference), also, it costs nothing to upload archives to the internet archive.

**Comment by mwpenny** [comment]
Those at Internet Archive work there as their job. Regardless, I do not have archived copies of issues from the original repo.

Hackgrid is the one who logged that issue he linked to (https://web.archive.org/web/20240104142322/https://github.com/lambertjamesd/portal64/issues).

**Comment by mwpenny** [comment]
Closing based on discussion in #84
