### ISSUE TITLE
Trouble with building rom

### ISSUE THREAD

**Issue by kiperjennmaid** [mwpenny/portal64-still-alive#87]
Hi I'm new to Linux and ROM building in general. Ive downloaded the zip and followed the instructions but it ends up with an error and I'm stuck now. If y'all can please help me build the ROM because Im excited to play it after finding out this project is still alive. 
![Screenshot from 2024-09-01 14-59-18](https://github.com/user-attachments/assets/6468548c-b695-4308-b151-1c8825ef9410)

**Comment by hackgrid** [comment]
If you want to build via docker, then you need install docker first.

otherwise, just follow these instructions
https://github.com/mwpenny/portal64-still-alive?tab=readme-ov-file#how-to-build

and ignore the alternative ones

**Comment by hackgrid** [comment]
You did not follow the main instructions if you enter docker stuff.
Please follow the instructions from the main readme and enter each line separately instead of copying whole blocks of code into the console.

**Comment by mwpenny** [comment]
Since you're new to Linux, I think using Docker will be easiest. The instructions are here: https://github.com/mwpenny/portal64-still-alive/blob/master/documentation/docker_setup.md

make sure you install Docker, which is explained at the beginning

**Comment by kiperjennmaid** [comment]
ok ill try the docker ill let yall know how it goes

**Comment by kiperjennmaid** [comment]
On the website it says docker is not supported on Ubuntu version 24.04 which is a problem since that is the version I'm using

**Comment by mwpenny** [comment]
That's very odd because 24.04 is the LTS (long term support) version. Could you link to where you are seeing this?

**Comment by kiperjennmaid** [comment]
the is the website https://docs.docker.com/desktop/install/ubuntu/

**Comment by mwpenny** [comment]
This is referring to Docker Desktop, which is a graphical interface for Docker.

Docker is supported as listed here https://docs.docker.com/engine/install/ubuntu/

**Comment by kiperjennmaid** [comment]
ahhhhh ok tysm

**Comment by mwpenny** [comment]
Closing this based on the previous reply and lack of response.
